spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:postgresql://db:5432/bus_booking
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=XW/dOYwL67sMPry8YofjPITGytB6xpFFzBsK0lC5hyOfhKZciyIPQN3IpHbYFynwp5PhfyJgWEfPGtvlhBBeiQ==
jwt.expiration=86400000